# Homebrew Bundle manifest — the single list of everything Homebrew installs.
# brew.sh installs this with `brew bundle`, or run it yourself:
#   brew bundle install --file=~/dotfiles/Brewfile
# Docs: https://docs.brew.sh/Brew-Bundle-and-Brewfile

tap "charmbracelet/tap"

# CLI packages
brew "bash"
brew "betterleaks"
brew "cairo"
brew "charmbracelet/tap/freeze"
brew "coreutils"
brew "d2"
brew "dust"
brew "exiftool"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git"
brew "gitleaks"
brew "imagemagick"
brew "just"
brew "node"
brew "ocrmypdf"
brew "pkgconf"
brew "poppler"
brew "pre-commit"
brew "python"
brew "python-tk"
brew "ripgrep"
brew "tcl-tk"
brew "tealdeer"
brew "tesseract"
brew "tree"
brew "typst"
brew "uv"
brew "vhs"
brew "zsh"

# Apps
cask "brave-browser"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "codex"
cask "copilot-cli"
cask "discord"
cask "docker-desktop"
cask "firefox"
cask "gcloud-cli"
cask "gimp"
cask "git-credential-manager"
cask "google-chrome"
cask "google-drive"
cask "keyboardcleantool"
cask "libreoffice"
cask "postman"
cask "rectangle"
cask "spotify"
cask "visual-studio-code"
cask "vlc"

# Fonts
cask "font-architects-daughter"
cask "font-caveat"
cask "font-fontawesome"
cask "font-josefin-sans"
cask "font-lato"
cask "font-montserrat"
cask "font-nunito"
cask "font-open-sans"
cask "font-oswald"
cask "font-playfair-display"
cask "font-poppins"
cask "font-quicksand"
cask "font-raleway"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-varela-round"
